export const recipe = {
	CREATE_RECIPE: "CREATE_RECIPE",
	SELECT_RECIPE: "SELECT_RECIPE",
	FETCH_RECIPES: "FETCH_RECIPES",
	FETCH_RECIPE: "FETCH_RECIPE",
	EDIT_RECIPE: "EDIT_RECIPE",
	DELETE_RECIPE: "DELETE_RECIPE",
	CURRENT_RECIPE: "CURRENT_RECIPE",
};
